import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { Zap, Brain, TrendingUp, Shield, Dumbbell, Salad, Bot, ChevronRight, Sparkles, ArrowRight } from 'lucide-react';

const features = [
  {
    icon: Dumbbell,
    title: 'Workout Tracker',
    desc: 'Log workouts, track sets, reps, and calories burned with ease. Analyze week-over-week trends.',
    gradient: 'from-indigo-500 to-blue-500',
    glow: 'rgba(99,102,241,0.2)',
    border: 'rgba(99,102,241,0.3)',
  },
  {
    icon: Salad,
    title: 'Diet & Nutrition',
    desc: 'Monitor macros, calories, and fiber. Visualize your daily nutrition breakdown at a glance.',
    gradient: 'from-cyan-500 to-teal-500',
    glow: 'rgba(34,211,238,0.2)',
    border: 'rgba(34,211,238,0.3)',
  },
  {
    icon: Bot,
    title: 'AI Coach',
    desc: 'Chat with your personal AI fitness coach for real-time, personalized guidance and motivation.',
    gradient: 'from-purple-500 to-pink-500',
    glow: 'rgba(168,85,247,0.2)',
    border: 'rgba(168,85,247,0.3)',
  },
  {
    icon: TrendingUp,
    title: 'Progress Tracking',
    desc: 'Visualize body measurements, weight trends, and milestones with interactive charts.',
    gradient: 'from-emerald-500 to-green-500',
    glow: 'rgba(16,185,129,0.2)',
    border: 'rgba(16,185,129,0.3)',
  },
  {
    icon: Brain,
    title: 'AI Plan Generator',
    desc: 'Get a complete personalized weekly workout and diet plan generated by AI in seconds.',
    gradient: 'from-amber-500 to-orange-500',
    glow: 'rgba(245,158,11,0.2)',
    border: 'rgba(245,158,11,0.3)',
  },
  {
    icon: Shield,
    title: 'Streaks & Badges',
    desc: 'Earn XP, unlock achievement badges, and maintain daily streaks to stay motivated.',
    gradient: 'from-rose-500 to-red-500',
    glow: 'rgba(244,63,94,0.2)',
    border: 'rgba(244,63,94,0.3)',
  },
];

const stats = [
  { value: '50K+', label: 'Active Users' },
  { value: '95%', label: 'Goal Success Rate' },
  { value: '10M+', label: 'Workouts Logged' },
  { value: '4.9★', label: 'User Rating' },
];

const LandingPage = () => {
  return (
    <div className="min-h-screen bg-grid" style={{ background: 'var(--bg-primary)' }}>

      {/* ── Navbar ──────────────────────────────────────── */}
      <nav
        className="fixed top-0 left-0 right-0 z-50"
        style={{
          background: 'rgba(8, 12, 24, 0.88)',
          backdropFilter: 'blur(24px)',
          borderBottom: '1px solid rgba(99,102,241,0.12)',
        }}
      >
        <div className="page-container flex items-center justify-between h-16">
          {/* Logo */}
          <Link to="/" className="flex items-center gap-2.5 no-underline flex-shrink-0">
            <div className="w-8 h-8 rounded-lg flex items-center justify-center"
              style={{ background: 'linear-gradient(135deg, var(--primary), var(--accent))' }}>
              <Zap size={16} color="#fff" fill="#fff" />
            </div>
            <span className="font-display font-black text-lg gradient-text">FitMind AI</span>
          </Link>

          {/* Nav actions */}
          <div className="flex items-center gap-3">
            <Link to="/login" className="btn-secondary text-sm px-4 py-2">Sign In</Link>
            <Link to="/signup" className="btn-primary text-sm px-5 py-2">
              Get Started <ChevronRight size={15} />
            </Link>
          </div>
        </div>
      </nav>

      {/* ── Hero ──────────────────────────────────────────── */}
      <section className="relative overflow-hidden" style={{ paddingTop: '11rem', paddingBottom: '7rem' }}>
        {/* Background orbs */}
        <div className="absolute top-0 left-1/2 -translate-x-1/2 pointer-events-none select-none">
          <div className="w-[800px] h-[600px] rounded-full opacity-[0.07] blur-[100px]"
            style={{ background: 'radial-gradient(circle, var(--primary), transparent 65%)' }} />
        </div>
        <div className="absolute top-32 left-[15%] w-72 h-72 rounded-full opacity-[0.06] blur-[80px] pointer-events-none"
          style={{ background: 'radial-gradient(circle, var(--accent), transparent 70%)' }} />
        <div className="absolute top-20 right-[10%] w-64 h-64 rounded-full opacity-[0.05] blur-[80px] pointer-events-none"
          style={{ background: 'radial-gradient(circle, var(--purple), transparent 70%)' }} />

        <div className="page-container text-center relative z-10">
          {/* Pill badge */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
          >
            <span className="badge badge-primary text-xs mb-8 inline-flex px-3.5 py-1.5 gap-1.5">
              <Sparkles size={13} />
              AI-Powered Fitness Platform 2026
            </span>
          </motion.div>

          {/* Headline */}
          <motion.h1
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1, duration: 0.7 }}
            className="font-display text-5xl md:text-7xl font-black mb-6 leading-[1.1] tracking-tight max-w-5xl mx-auto"
          >
            Your{' '}
            <span className="gradient-text">AI Fitness Coach</span>
            <br className="hidden md:block" />
            Trained for You
          </motion.h1>

          {/* Subtext */}
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.25, duration: 0.6 }}
            className="text-lg md:text-xl max-w-2xl mx-auto mb-12 leading-relaxed"
            style={{ color: 'var(--text-secondary)' }}
          >
            Track workouts, log nutrition, generate AI plans, and monitor progress —
            all inside a beautifully unified dashboard built for serious athletes.
          </motion.p>

          {/* CTAs */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.35, duration: 0.6 }}
            className="flex flex-col sm:flex-row items-center justify-center gap-4"
          >
            <Link to="/signup" className="btn-primary text-base px-8 py-3.5 w-full sm:w-auto">
              Start Free — No Credit Card <ArrowRight size={17} />
            </Link>
            <Link to="/login" className="btn-secondary text-base px-8 py-3.5 w-full sm:w-auto text-center">
              Sign In
            </Link>
          </motion.div>

          {/* Stats */}
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.5, duration: 0.6 }}
            className="mt-20 flex items-center justify-center flex-wrap gap-x-10 gap-y-8"
          >
            {stats.map(({ value, label }, i) => (
              <div key={i} className="text-center">
                <p className="font-display text-3xl sm:text-4xl font-black gradient-text">{value}</p>
                <p className="text-sm mt-1" style={{ color: 'var(--text-muted)' }}>{label}</p>
              </div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* ── Divider ─────────────────────────────────────── */}
      <div className="divider mx-auto" style={{ maxWidth: '80rem' }} />

      {/* ── Features Grid ───────────────────────────────── */}
      <section className="py-28">
        <div className="page-container">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="section-header"
          >
            <span className="badge badge-accent mb-4 inline-flex">Features</span>
            <h2>Everything You <span className="gradient-text">Need</span></h2>
            <p>A complete AI-powered ecosystem for your fitness journey — from training to nutrition to gamification.</p>
          </motion.div>

          <div className="card-grid-3">
            {features.map(({ icon: Icon, title, desc, gradient, glow, border }, i) => (
              <motion.div
                key={title}
                initial={{ opacity: 0, y: 32 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.07, duration: 0.5 }}
                className="glass-card-hover p-7 flex flex-col gap-5"
              >
                <div
                  className="w-12 h-12 rounded-xl flex items-center justify-center flex-shrink-0"
                  style={{
                    background: `linear-gradient(135deg, ${glow.replace('0.2', '0.25')}, transparent)`,
                    border: `1px solid ${border}`,
                    boxShadow: `0 0 16px ${glow}`,
                  }}
                >
                  <Icon size={22} style={{ color: 'white' }} strokeWidth={1.8} />
                </div>
                <div>
                  <h3 className="font-bold text-lg mb-2" style={{ color: 'var(--text-primary)' }}>{title}</h3>
                  <p className="text-sm leading-relaxed" style={{ color: 'var(--text-secondary)' }}>{desc}</p>
                </div>
                <div className="mt-auto pt-2">
                  <Link to="/signup" className="inline-flex items-center gap-1 text-xs font-semibold primary-text hover:gap-2 transition-all duration-200">
                    Learn more <ArrowRight size={12} />
                  </Link>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── How It Works ────────────────────────────────── */}
      <section className="py-24" style={{ background: 'rgba(99,102,241,0.03)' }}>
        <div className="page-container">
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            className="section-header"
          >
            <span className="badge badge-primary mb-4 inline-flex">How It Works</span>
            <h2>Get Started in <span className="gradient-text">3 Steps</span></h2>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-4xl mx-auto">
            {[
              { step: '01', title: 'Create Profile', desc: 'Sign up and enter your fitness data — goals, weight, height, and activity level.' },
              { step: '02', title: 'Get Your AI Plan', desc: 'Our AI generates a custom workout and meal plan tailored to your exact profile.' },
              { step: '03', title: 'Track & Level Up', desc: 'Log daily activities, earn XP, maintain streaks, and watch your progress soar.' },
            ].map(({ step, title, desc }, i) => (
              <motion.div
                key={step}
                initial={{ opacity: 0, y: 24 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className="relative text-center"
              >
                <div className="w-14 h-14 rounded-2xl glass-card flex items-center justify-center mx-auto mb-5"
                  style={{ border: '1px solid var(--border)' }}>
                  <span className="font-display font-black text-xl gradient-text">{step}</span>
                </div>
                <h3 className="font-bold text-lg mb-2" style={{ color: 'var(--text-primary)' }}>{title}</h3>
                <p className="text-sm leading-relaxed" style={{ color: 'var(--text-secondary)' }}>{desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── CTA Banner ──────────────────────────────────── */}
      <section className="py-28">
        <div className="page-container">
          <motion.div
            initial={{ opacity: 0, scale: 0.97 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            transition={{ duration: 0.55 }}
            className="glass-card relative overflow-hidden text-center mx-auto py-20 px-8 md:px-16"
            style={{ maxWidth: '56rem', border: '1px solid rgba(99,102,241,0.2)' }}
          >
            {/* Glow blobs */}
            <div className="absolute -top-24 -right-24 w-72 h-72 rounded-full blur-3xl pointer-events-none opacity-10"
              style={{ background: 'var(--primary)' }} />
            <div className="absolute -bottom-24 -left-24 w-72 h-72 rounded-full blur-3xl pointer-events-none opacity-10"
              style={{ background: 'var(--accent)' }} />

            <div className="relative z-10">
              <span className="badge badge-primary mb-6 inline-flex">Join 50,000+ Athletes</span>
              <h2 className="font-display text-4xl md:text-5xl font-black mb-5 leading-tight" style={{ color: 'var(--text-primary)' }}>
                Ready to <span className="gradient-text">Transform?</span>
              </h2>
              <p className="mb-10 text-lg max-w-xl mx-auto" style={{ color: 'var(--text-secondary)' }}>
                Join thousands achieving their fitness goals with personalized AI guidance. Start free today.
              </p>
              <Link to="/signup" className="btn-primary text-base px-10 py-4 inline-flex items-center gap-2">
                Start Your Journey <ArrowRight size={18} />
              </Link>
            </div>
          </motion.div>
        </div>
      </section>

      {/* ── Footer ──────────────────────────────────────── */}
      <footer style={{ borderTop: '1px solid var(--border-subtle)' }} className="py-8">
        <div className="page-container flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <div className="w-6 h-6 rounded-md flex items-center justify-center"
              style={{ background: 'linear-gradient(135deg, var(--primary), var(--accent))' }}>
              <Zap size={12} color="#fff" fill="#fff" />
            </div>
            <span className="font-bold text-sm gradient-text">FitMind AI</span>
          </div>
          <p className="text-xs" style={{ color: 'var(--text-muted)' }}>© 2026 FitMind AI. Built for champions. 🚀</p>
          <div className="flex items-center gap-4">
            <Link to="/login" className="text-xs hover:text-white transition-colors" style={{ color: 'var(--text-muted)' }}>Login</Link>
            <Link to="/signup" className="text-xs hover:text-white transition-colors" style={{ color: 'var(--text-muted)' }}>Sign Up</Link>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default LandingPage;
